package com.telappoint.resvdeskrestws.admin.constants;

/**
 * @author Balaji
 */
public enum AdminFlowStateConstants {
	GET_ADMIN_LOCATION_LIST("GET_ADMIN_LOCATION_LIST"), 
	GET_LOCATION_BY_ID("GET_LOCATION_BY_ID"),
	DELETE_LOCATION("DELETE_LOCATION"),
	OPEN_CLOSE_LOCATION("OPEN_CLOSE_LOCATION"),
	ADD_LOCATION("ADD_LOCATION"),
	UPDATE_LOCATION("UPDATE_LOCATION"),
	
	GET_ADMIN_EVENT_LIST("GET_ADMIN_EVENT_LIST"), 
	DELETE_EVENT("DELETE_EVENT"),
	GET_EVENT_BY_ID("GET_EVENT_BY_ID"),
	OPEN_CLOSE_EVENT("OPEN_CLOSE_EVENT"),
	ADD_EVENT("ADD_EVENT"),
	UPDATE_EVENT("UPDATE_EVENT"),
	GET_DIALER_SETTING("GET_DIALER_SETTING"),
	GET_INBOUND_CALL_REPORT_LIST("GET_INBOUND_CALL_REPORT_LIST"),
	GET_OUTBOUND_CALL_REPORT_LIST("GET_OUTBOUND_CALL_REPORT_LIST"),
	GET_TRANS_STATS_LIST("GET_TRANS_STATS_LIST"),
	
	
	GET_ADMIN_EVENT_DATE_TIME_LIST("GET_ADMIN_EVENT_DATE_TIME_LIST"), 
	DELETE_EVENT_DATE_TIME("DELETE_EVENT_DATE_TIME"),
	OPEN_CLOSE_EVENT_DATE_TIME("OPEN_CLOSE_EVENT_DATE_TIME"),
	ADD_EVENT_DATE_TIME("ADD_EVENT_DATE_TIME"),
	UPDATE_EVENT_DATE_TIME("UPDATE_EVENT_DATE_TIME"),
	CHANGE_SCHEDULER_STATUS("CHANGE_SCHEDULER_STATUS"),
	
	GET_CAMPAIGN_BY_ID("GET_CAMPAIGN_BY_ID"),
	GET_CAMPAIGNS("GET_CAMPAIGNS"),
	GET_RESERVATION_STATUS_LIST("GET_RESERVATION_STATUS_LIST"),
	GET_REMINDER_STATUS_LIST("GET_REMINDER_STATUS_LIST"),
	UPDATE_REMINDER_STATUS("UPDATE_REMINDER_STATUS"),
	GET_NOTIFY_LIST("GET_NOTIFY_LIST"),
	
	ADD_RESV_REPORT_CONFIG("ADD_RESV_REPORT_CONFIG"),
	GET_RESV_REPORT_CONFIG("GET_RESV_REPORT_CONFIG"),
	DELETE_REPORT_CONFIG_BY_ID("DELETE_REPORT_CONFIG_BY_ID"),
	
	GET_ADMIN_CALENDAR_OVERVIEW_LIST("GET_ADMIN_CALENDAR_OVERVIEW_LIST"),
	SEATS_CALENDAR_VIEW("SEATS_CALENDAR_VIEW"),
	SEATS_CALENDAR_TIME_LIST("SEATS_CALENDAR_TIME_LIST"),
	DAILY_CALENDAR_VIEW("DAILY_CALENDAR_VIEW"),
	MONTHLY_CALENDAR_VIEW("MONTHLY_CALENDAR_VIEW"),
	GET_DATE_LIST("GET_DATE_LIST"),
	GET_HOME_PAGE_DETAILS("GET_HOME_PAGE_DETAILS"),
	GET_CUSTOMER_NAMES("GET_CUSTOMER_NAMES"),
	VALIDATE_EVENT_DATE_TIME("VALIDATE_EVENT_DATE_TIME"),
	UPDATE_EVENT_SEATS("UPDATE_EVENT_SEATS"),
	RESERVATION_REPORTS("RESERVATION_REPORTS"),
	CALENDAR_OVERVIEW_DETAILS("CALENDAR_OVERVIEW_DETAILS"),
	GET_CUSTOMER_ID("GET_CUSTOMER_ID"),
	FUTURE_RESERVATION_DETAILS("FUTURE_RESERVATION_DETAILS"),
	PAST_RESERVATION_DETAILS("PAST_RESERVATION_DETAILS"),
	RESERVATION_DETAILS("RESERVATION_DETAILS"),
	RESERVATION_SEARCH("RESERVATION_SEARCH"),
	TABLE_PRINT_VIEW("TABLE_PRINT_VIEW"),
	UPDATE_CUSTOMER("UPDATE_CUSTOMER"),
	DYNAMIC_SEARCH_FIELDS("DYNAMIC_SEARCH_FIELDS"),
	CLIENT_DETAILS("CLIENT_DETAILS"),
	BLOCKED_CLIENT_DETAILS("BLOCKED_CLIENT_DETAILS"),
	GRAPH_DETAILS("GRAPH_DETAILS"),
	PRIVILAGE_DETAILS("PRIVILAGE_DETAILS"),
	RESERVATION_REMINDERS("RESERVATION_REMINDERS"),
	
	PHONE_LOG_UPLOAD("PHONE_LOG_UPLOAD"),
	NOTIFY_PHONE_STATUS("NOTIFY_PHONE_STATUS"),
	
	UPDATE_SCREENED_STAUS("UPDATE_SCREENED_STAUS"),
	UPDATE_SEAT_RESERVED_STAUS("UPDATE_SEAT_RESERVED_STAUS");

	private String value;

	private AdminFlowStateConstants(String value) {
		this.setValue(value);
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
}
