package com.telappoint.resvdeskrestws.common.constants;

/**
 * @author Balaji
 */
public enum DisplayPageContentConstants {

	LEFT_SIDE_TOP_WELCOME_HEADER("LEFT_SIDE_TOP_WELCOME_HEADER"),
	
	// login page - LOGIN FIRST RIGHT SIDE PAGE CONTENT
	RIGHT_SIDE_LOGIN_FIRST_LOGININFO_PAGE_CONTENT("RIGHT_SIDE_LOGIN_FIRST_LOGININFO_PAGE_CONTENT"),
	RIGHT_SIDE_LOGIN_FIRST_RESV_DETAILS_CONTENT("RIGHT_SIDE_LOGIN_FIRST_RESV_DETAILS_CONTENT"),
	RIGHT_SIDE_LOGIN_FIRST_RESV_VERIFY_PAGE_CONTENT("RIGHT_SIDE_LOGIN_FIRST_RESV_VERIFY_PAGE_CONTENT"),
	RIGHT_SIDE_LOGIN_FIRST_CONFIRMATION_PAGE_CONTENT("RIGHT_SIDE_LOGIN_FIRST_CONFIRMATION_PAGE_CONTENT"),
	
	// LOGIN LAST RIGHT SIDE PAGE CONTENT
	RIGHT_SIDE_LOGIN_LAST_LOGININFO_PAGE_CONTENT("RIGHT_SIDE_LOGIN_LAST_LOGININFO_PAGE_CONTENT"),
	RIGHT_SIDE_LOGIN_LAST_RESV_DETAILS_CONTENT("RIGHT_SIDE_LOGIN_LAST_RESV_DETAILS_CONTENT"),
	RIGHT_SIDE_LOGIN_LAST_RESV_VERIFY_PAGE_CONTENT("RIGHT_SIDE_LOGIN_LAST_RESV_VERIFY_PAGE_CONTENT"),
	RIGHT_SIDE_LOGIN_LAST_CONFIRMATION_PAGE_CONTENT("RIGHT_SIDE_LOGIN_LAST_CONFIRMATION_PAGE_CONTENT"),
	
	LEFT_SIDE_LOGIN_HEADER("LEFT_SIDE_LOGIN_HEADER"),
	LEFT_SIDE_RESV_DETAILS_HEADER("LEFT_SIDE_RESV_DETAILS_HEADER"),
	LEFT_SIDE_RESV_VERIFY_HEADER("LEFT_SIDE_RESV_VERIFY_HEADER"),
	LEFT_SIDE_CONFIRM_HEADER("LEFT_SIDE_CONFIRM_HEADER"),
	
	// Reservation details page
	RIGHT_SIDE_EVENT_HISTORY_HEADER("RIGHT_SIDE_EVENT_HISTORY_HEADER"),	
	RIGHT_SIDE_LIST_OF_THING_BRING_HEADER("RIGHT_SIDE_LIST_OF_THING_BRING_HEADER"),
	RIGHT_SIDE_CONTACT_DETAILS_HEADER("RIGHT_SIDE_CONTACT_DETAILS_HEADER"),
	
	
	// schedule closed page content 
	CLOSED_PAGE_HEADER_TEXT_LEGEND("CLOSED_PAGE_HEADER_TEXT_LEGEND"),
	CLOSED_LANDING_PAGE_TEXT_LEGEND("CLOSED_PAGE_HEADER_TEXT_LEGEND"),
	NO_FUNDING_PAGE_HEADER_TEXT_LEGEND("NO_FUNDING_PAGE_HEADER_TEXT_LEGEND"),
	NO_FUNDING_PAGE_TEXT_LEGEND("NO_FUNDING_PAGE_TEXT_LEGEND"),
	LANDING_PAGE_CONTENT("LANDING_PAGE_CONTENT"),
	VIEW_EXISTING_RESV_LABEL("VIEW_EXISTING_RESV_LABEL");
	
	
	private String value;
	private DisplayPageContentConstants(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}
}
