package com.telappoint.resvdeskrestws.common.constants;

/**
 * @author Balaji
 */
public enum DisplayFieldLabelConstants {

	// login page
	LOGIN_SSN("LOGIN_SSN"),
	LOGIN_SSN_EMPTY_ERROR("LOGIN_SSN_EMPTY_ERROR"), 
	LOGIN_SSN_INVALID_ERROR("LOGIN_SSN_INVALID_ERROR"),
	LOGIN_CONTACT_PHONE("LOGIN_CONTACT_PHONE"),
	LOGIN_CONTACT_PHONE_EMPTY_ERROR("LOGIN_CONTACT_PHONE_EMPTY_ERROR"),
	LOGIN_CONTACT_PHONE_INVALID_ERROR("LOGIN_CONTACT_PHONE_INVALID_ERROR"),
	LOGIN_EMAIL("LOGIN_EMAIL"), 
	LOGIN_EMAIL_EMPTY_ERROR("LOGIN_EMAIL_EMPTY_ERROR"),
	LOGIN_EMAIL_INVALID_ERROR("LOGIN_EMAIL_INVALID_ERROR"),

	// Reservation details page
	RESV_COMPANY("RESV_COMPANY"),
	RESV_COMPANY_EMPTY("RESV_COMPANY_EMPTY"),
	RESV_COMPANY_ERROR("RESV_COMPANY_ERROR"),
	
	RESV_PROCEDURE("RESV_PROCEDURE"),
	RESV_PROCEDURE_EMPTY("RESV_PROCEDURE_EMPTY"),
	RESV_PROCEDURE_ERROR("RESV_PROCEDURE_ERROR"),
	
	RESV_LOCATION("RESV_LOCATION"),
	RESV_LOCATION_EMPTY("RESV_LOCATION_EMPTY"),
	RESV_LOCATION_ERROR("RESV_LOCATION_ERROR"),
	
	RESV_DEPARTMENT("RESV_DEPARTMENT"),
	RESV_DEPARTMENT_EMPTY("RESV_DEPARTMENT_EMPTY"),
	RESV_DEPARTMENT_ERROR("RESV_DEPARTMENT_ERROR"),
	
	RESV_EVENT("RESV_EVENT"),
	RESV_EVENT_EMPTY("RESV_EVENT_EMPTY"),
	RESV_EVENT_ERROR("RESV_EVENT_ERROR"),
	
	RESV_SEAT("RESV_SEAT"),
	RESV_SEAT_EMPTY("RESV_SEAT_EMPTY"),
	RESV_SEAT_ERROR("RESV_SEAT_ERROR"),
	
	RESV_DATE("RESV_DATE"),
	RESV_DATE_EMPTY("RESV_DATE_EMPTY"),
	RESV_DATE_ERROR("RESV_DATE_ERROR"),
	RESV_TIME("RESV_TIME"),
	RESV_TIME_ERROR("RESV_TIME_ERROR"),
	
	RESV_SELECT_COMPANY_LABEL("RESV_SELECT_COMPANY_LABEL"),
	RESV_SELECT_PROCEDURE_LABEL("RESV_SELECT_PROCEDURE_LABEL"),
	RESV_SELECT_LOCATION_LABEL("RESV_SELECT_LOCATION_LABEL"),
	RESV_SELECT_DEPARTMENT_LABEL("RESV_SELECT_DEPARTMENT_LABEL"),
	RESV_SELECT_EVENT_LABEL("RESV_SELECT_EVENT_LABEL"),
	RESV_SELECT_DATE_LABEL("RESV_SELECT_DATE_LABEL"),
	RESV_SELECT_TIME_LABEL("RESV_SELECT_TIME_LABEL"),
	RESV_SELECT_SEAT_LABEL("RESV_SELECT_SEAT_LABEL"),
	
	// confirm page constants
	RESV_CUST_NAME("RESV_CUST_NAME"),
	RESV_CONFIRMATION_NO("RESV_CONFIRMATION_NO"),
	
	// contact details labels
	
	RIGHT_SIDE_EMAIL_LABEL("RIGHT_SIDE_EMAIL_LABEL"),
	RIGHT_SIDE_WEBSITE_LABEL("RIGHT_SIDE_WEBSITE_LABEL");
	
	
	private String value;

	private DisplayFieldLabelConstants(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}
}
