package com.telappoint.resvdeskrestws.common.constants;

/**
 * @author Balaji
 */
public enum FlowStateConstants {
	DB_ERROR("9999"),
	
	GET_CLIENT("GET_CLIENT"), 
	GET_LOGIN_INFO("GET_LOGIN_INFO"),
	GET_REGISTRATION_INFO("GET_REGISTRATION_INFO"),
	AUTH_CUSTOMER("AUTH_CUSTOMER"),
	GET_RESV_DETAILS_SEL_INFO("GET_RESV_DETAILS_SEL_INFO"),
	GET_COMPANY_LIST("GET_COMPANY_LIST"), 
	GET_PROCEDURE_LIST("GET_PROCEDURE_LIST"),

	GET_LOCATION_LIST("GET_LOCATION_LIST"),
	GET_DEPARTMENT_LIST("GET_DEPARTMENT_LIST"),
	GET_EVENT_LIST("GET_EVENT_LIST"),
	GET_EVENT_DATES_LIST("GET_EVENT_DATES_LIST"), 
	GET_EVENT_TIMES("GET_EVENT_TIMES"),
	GET_EVENT_SEATS("GET_EVENT_SEATS"),
	GET_NOTIFICATION_LIST("GET_NOTIFICATION_LIST"),
	
	HOLD_RESERVATION("HOLD_RESERVATION"),
	GET_VERIFY_RESERVATION("GET_VERIFY_RESERVATION"),
	CONFIRM_RESERVATION("CONFIRM_RESERVATION"),
	CANCEL_RESERVATION("CANCEL_RESERVATION"),
	HOLD_RELEASE_EVENT_TIME("HOLD_RELEASE_EVENT_TIME"),
	GET_NAME_RECORD_VXML("GET_NAME_RECORD_VXML"),
	UPDATE_RECORD_VXML("UPDATE_RECORD_VXML"),
	LIST_OF_THINGS_TO_BRING("LIST_OF_THINGS_TO_BRING"),
	CONF_PAGE_CONTACTS_DETAILS("CONF_PAGE_CONTACTS_DETAILS"),
	GET_EVENT_HISTORY("GET_EVENT_HISTORY"),
	GET_RESERVED_EVENTS("GET_RESERVED_EVENTS"),
	
	LOGININFO_PAGE_RIGHT_SIDE_CONTENT("LOGININFO_PAGE_RIGHT_SIDE_CONTENT"),
	RESV_DETAILS_RIGHT_SIDE_CONTENT("RESV_DETAILS_RIGHT_SIDE_CONTENT"),
	RESV_VERIFY_PAGE_RIGHT_SIDE_CONTENT("RESV_VERIFY_PAGE_RIGHT_SIDE_CONTENT"),
	CONFIRMATION_PAGE_RIGHT_SIDE_CONTENT("CONFIRMATION_PAGE_RIGHT_SIDE_CONTENT"),
	SPECIFIC_DATE("SPECIFIC_DATE"),
	DISCONNECT_VXML("DISCONNECT_VXML"),
	SAVE_UPDATE_IVR_CALL("SAVE_UPDATE_IVR_CALL"),
	CHECK_ALLOW_DUPLICATE_RESV("CHECK_ALLOW_DUPLICATE_RESV"),
	
	NO_APPT_ALL_LOC("NO_APPT_ALL_LOC"),
	NO_APPT_SELECTED_LOCATION("NO_APPT_SELECTED_LOC"),
	NO_APPT_SELECTED_EVENT("NO_APPT_SELECTED_EVENT"),
	NO_APPT_SELECTED_DATE("NO_APPT_SELECTED_DATE"),
	NO_APPT_SELECTED_TIME("NO_APPT_SELECTED_TIME"),
	
	// notification constants.
	LOCK_DIALER_LOCK("LOCK_DIALER_LOCK"),
	UNLOCK_DIALER_LOCK("UNLOCK_DIALER_LOCK");
	

	private String value;
	
	private FlowStateConstants(String value) {
		this.setValue(value);
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
}
